// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' as firebase_core;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static firebase_core.FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const firebase_core.FirebaseOptions android =
      firebase_core.FirebaseOptions(
        apiKey: 'AIzaSyCSeUmPD3EtmKXRpJXiyIg0pnDOCuWR3Es',
        appId: '1:1041537629658:android:4f4fa6e6b4dc58868d54e3',
        messagingSenderId: '1041537629658',
        projectId: 'video-fake-call-app-ab',
        storageBucket: 'video-fake-call-app-ab.firebasestorage.app',
      );

  static const firebase_core.FirebaseOptions ios =
      firebase_core.FirebaseOptions(
        apiKey: 'AIzaSyAhedGZcGvHT34JcU6UZTF_D8v7mkASsng',
        appId: '1:597515759959:ios:14aee6ed71747566228e12',
        messagingSenderId: '597515759959',
        projectId: 'prank-video-call-f1f9a',
        storageBucket: 'prank-video-call-f1f9a.firebasestorage.app',
        iosBundleId: 'com.fynotech.prankcall',
      );
}
